tasks = {
    1: "Walk 10,000 steps",
    2: "Wake up 1 hour earlier",
    3: "Cold shower for 30 seconds",
    4: "No sugar for the entire day",
    5: "30 minutes workout",
    6: "Stretch or yoga for 20 minutes",
    7: "Digital detox for 6 hours",
    8: "Run 2 km",
    9: "Skip junk food today",
    10: "Hold plank for 2 minutes",
    11: "Learn basic meditation",
    12: "Walk alone without phone",
    13: "Sleep before 10:30 PM",
    14: "Write goals on paper",
    15: "50 pushups (split allowed)",
    16: "Drink 3 liters of water",
    17: "Clean your room completely",
    18: "No complaining for the day",
    19: "Learn 5 new words",
    20: "20 minutes silence",
    21: "5 km walk or run",
    22: "Try a new healthy recipe",
    23: "1 hour deep work",
    24: "30 minutes core workout",
    25: "Write one handwritten journal page",
    26: "Fix posture consciously all day",
    27: "No social media today",
    28: "Early morning walk",
    29: "Learn a breathing technique",
    30: "Reflect and plan next month",

    31: "Read 10 pages",
    32: "Learn keyboard shortcuts",
    33: "Solve 3 aptitude questions",
    34: "Speak to a stranger",
    35: "Watch a tech talk",
    36: "Summarize what you learned",
    37: "Learn Git basics",
    38: "Practice typing for 20 minutes",
    39: "Teach someone something",
    40: "Ask a question publicly",
    41: "Learn Python syntax",
    42: "Solve one coding problem",
    43: "Explain code aloud",
    44: "No phone till noon",
    45: "Learn time-blocking",
    46: "Revise DSA basics",
    47: "Attend a webinar",
    48: "Write a LinkedIn post",
    49: "Learn one Excel shortcut",
    50: "Answer one mock interview question",
    51: "Improve one resume line",
    52: "Practice explaining a problem",
    53: "Learn a memory technique",
    54: "Speed read 5 pages",
    55: "Learn one Linux command",
    56: "Build a mini script",
    57: "Read about an AI trend",
    58: "Practice speaking for 5 minutes",
    59: "Learn recursion concept",
    60: "Weekly self-review",

    61: "Solve a medium-level problem",
    62: "Learn SQL basics",
    63: "Teach DSA to a friend",
    64: "Debug old code",
    65: "Learn one design pattern",
    66: "Improve GitHub profile",
    67: "Watch interview experience video",
    68: "Practice whiteboard coding",
    69: "Learn a probability concept",
    70: "No multitasking today",
    71: "Build a small project idea",
    72: "Write clean comments",
    73: "Learn an ML concept",
    74: "Present a topic to mirror",
    75: "Practice articulation",
    76: "Learn API basics",
    77: "Read a tech blog",
    78: "Optimize an old solution",
    79: "Learn Big-O clearly",
    80: "Solve a timed problem",
    81: "Practice storytelling",
    82: "Learn data visualization",
    83: "Explain your project clearly",
    84: "Record yourself speaking",
    85: "Improve a weak topic",
    86: "Learn cloud basics",
    87: "Teach juniors a concept",
    88: "Prepare one mock HR answer",
    89: "Review last 3 months",
    90: "Set next targets",

    91: "Ask a doubt in class",
    92: "Speak 2 minutes impromptu",
    93: "Attend a meetup or event",
    94: "Network with one person",
    95: "Send a cold email to senior",
    96: "Share learning online",
    97: "Volunteer for a task",
    98: "Lead a small group",
    99: "Present a slide deck",
    100: "Face a fear",

    101: "Participate in a debate",
    102: "Conduct a mock interview",
    103: "Join a competition",
    104: "Handle rejection calmly",
    105: "Speak on a mic",
    106: "Teach a workshop topic",
    107: "Publish a mini project",
    108: "Ask for feedback",
    109: "Improve one weak habit",
    110: "Speak without notes",
    111: "Pitch an idea",
    112: "Mentor a junior",
    113: "Defend your opinion",
    114: "Explain tech to a non-tech person",
    115: "Practice negotiation",
    116: "Handle conflict maturely",
    117: "Lead a discussion",
    118: "Share a failure story",
    119: "Answer a tough question",
    120: "Deliver a 10-minute speech",

    121: "Join a hackathon",
    122: "Take responsibility for a task",
    123: "Speak confidently in English",
    124: "Teach on the board",
    125: "Ask for an opportunity",
    126: "Improve body language",
    127: "Explain an ML project",
    128: "Solve a problem live",
    129: "Handle a pressure task",
    130: "Share your vision publicly",
    131: "Conduct an interview",
    132: "Network on LinkedIn",
    133: "Apply for an internship",
    134: "Practice public speaking",
    135: "Lead a presentation",
    136: "Explain DSA orally",
    137: "Handle criticism",
    138: "Speak with authority",
    139: "Demo your project",
    140: "Take a leadership role",

    141: "Build team trust",
    142: "Facilitate a meeting",
    143: "Speak without filler words",
    144: "Teach a complex topic",
    145: "Address audience fear",
    146: "Improve storytelling",
    147: "Practice persuasive speech",
    148: "Answer rapid questions",
    149: "Speak on stage",
    150: "Mid-year reflection",

    151: "Conduct a seminar",
    152: "Debate confidently",
    153: "Defend your solution",
    154: "Lead a code review",
    155: "Pitch to a mentor",
    156: "Explain career goals",
    157: "Mock panel interview",
    158: "Speak under time limit",
    159: "Share personal vision",
    160: "Teach a full lesson",

    161: "Handle a tough audience",
    162: "Speak assertively",
    163: "Handle disagreement",
    164: "Public Q&A",
    165: "Speak spontaneously",
    166: "Own your mistakes",
    167: "Inspire others",
    168: "Run a discussion",
    169: "Give feedback",
    170: "Accept feedback",

    171: "Teach in simple words",
    172: "Explain system design",
    173: "Present without slides",
    174: "Lead from the front",
    175: "Speak confidently to seniors",
    176: "Conduct mock GD",
    177: "Answer tricky HR question",
    178: "Speak with clarity",
    179: "Build authority",
    180: "Full confidence audit",

    181: "Learn a new tech stack",
    182: "Build a real-world project",
    183: "Deploy your project",
    184: "Write a technical blog",
    185: "Teach online",
    186: "Mentor consistently",
    187: "Lead an initiative",
    188: "Handle failure calmly",
    189: "Speak at an event",
    190: "Crack a mock interview",

    191: "Optimize daily routine",
    192: "Solve an advanced DSA problem",
    193: "Learn system design basics",
    194: "Explain architecture",
    195: "Build a portfolio site",
    196: "Apply aggressively",
    197: "Handle rejection maturely",
    198: "Improve negotiation skills",
    199: "Speak with conviction",
    200: "Half-year reflection",

    201: "Build a startup idea",
    202: "Pitch your idea publicly",
    203: "Handle a pressure deadline",
    204: "Lead a full project",
    205: "Teach juniors weekly",
    206: "Speak fluently for 15 minutes",
    207: "Improve clarity and brevity",
    208: "Solve hard problems",
    209: "Explain AI ethically",
    210: "Create personal brand content",

    211: "Lead a team meeting",
    212: "Mentor an underperformer",
    213: "Own a big responsibility",
    214: "Speak without fear",
    215: "Publish a case study",
    216: "Build a discipline system",
    217: "Deep work for 3 hours",
    218: "Review failures",
    219: "Improve emotional control",
    220: "Learn an advanced ML concept",

    221: "Teach ML simply",
    222: "Explain trade-offs",
    223: "Answer 'Why you?' confidently",
    224: "Handle a tough interviewer",
    225: "Speak with impact",
    226: "Deliver a keynote-style talk",
    227: "Coach someone",
    228: "Solve a pressure interview",
    229: "Build leadership habits",
    230: "Design a long-term plan",

    231: "Speak with authenticity",
    232: "Handle conflict maturely",
    233: "Explain vision clearly",
    234: "Take ownership",
    235: "Inspire your team",
    236: "Teach consistently",
    237: "Build reputation",
    238: "Speak under stress",
    239: "Finalize career roadmap",
    240: "Mock final interview",

    241: "Improve weakest skill",
    242: "Speak without hesitation",
    243: "Lead a large group",
    244: "Build a confidence ritual",
    245: "Publish achievements",
    246: "Reflect deeply",
    247: "Teach an advanced topic",
    248: "Speak with authority",
    249: "Handle leadership pressure",
    250: "250-day review",

    251: "Push limits again",
    252: "Learn a totally new skill",
    253: "Teach that new skill",
    254: "Speak to a large audience",
    255: "Build an unstoppable routine",
    256: "Mentor at scale",
    257: "Lead vision execution",
    258: "Explain complex ideas simply",
    259: "Speak like a leader",
    260: "Execute without excuses",

    261: "Build long-term value",
    262: "Teach discipline",
    263: "Handle success humbly",
    264: "Master public speaking",
    265: "Coach others confidently",
    266: "Own your story",
    267: "Speak with clarity and calm",
    268: "Build legacy mindset",
    269: "Lead by example",
    270: "Execute under pressure",

    271: "Teach leadership",
    272: "Speak with influence",
    273: "Inspire action",
    274: "Handle big responsibility",
    275: "Design life system",
    276: "Communicate vision",
    277: "Speak fearlessly",
    278: "Build elite habits",
    279: "Master self-control",
    280: "Lead without title",

    281: "Teach mastery",
    282: "Speak like top 1%",
    283: "Solve the hardest problem",
    284: "Reflect on growth",
    285: "Raise standards",
    286: "Teach resilience",
    287: "Speak with wisdom",
    288: "Execute relentlessly",
    289: "Lead transformation",
    290: "Communicate impactfully",

    291: "Teach future leaders",
    292: "Speak with confidence",
    293: "Own your future",
    294: "Build unstoppable mindset",
    295: "Act without fear",
    296: "Teach courage",
    297: "Speak powerfully",
    298: "Live discipline daily",
    299: "Build excellence",
    300: "300-day audit",

    301: "Repeat hardest challenge with higher intensity",
    302: "Repeat hardest challenge with higher intensity",
    303: "Repeat hardest challenge with higher intensity",
    304: "Repeat hardest challenge with higher intensity",
    305: "Repeat hardest challenge with higher intensity",
    306: "Repeat hardest challenge with higher intensity",
    307: "Repeat hardest challenge with higher intensity",
    308: "Repeat hardest challenge with higher intensity",
    309: "Repeat hardest challenge with higher intensity",
    310: "Repeat hardest challenge with higher intensity",
    311: "Repeat hardest challenge with higher intensity",
    312: "Repeat hardest challenge with higher intensity",
    313: "Repeat hardest challenge with higher intensity",
    314: "Repeat hardest challenge with higher intensity",
    315: "Repeat hardest challenge with higher intensity",
    316: "Repeat hardest challenge with higher intensity",
    317: "Repeat hardest challenge with higher intensity",
    318: "Repeat hardest challenge with higher intensity",
    319: "Repeat hardest challenge with higher intensity",
    320: "Repeat hardest challenge with higher intensity",
    321: "Repeat hardest challenge with higher intensity",
    322: "Repeat hardest challenge with higher intensity",
    323: "Repeat hardest challenge with higher intensity",
    324: "Repeat hardest challenge with higher intensity",
    325: "Repeat hardest challenge with higher intensity",
    326: "Repeat hardest challenge with higher intensity",
    327: "Repeat hardest challenge with higher intensity",
    328: "Repeat hardest challenge with higher intensity",
    329: "Repeat hardest challenge with higher intensity",
    330: "Repeat hardest challenge with higher intensity",
    331: "Repeat hardest challenge with higher intensity",
    332: "Repeat hardest challenge with higher intensity",
    333: "Repeat hardest challenge with higher intensity",
    334: "Repeat hardest challenge with higher intensity",
    335: "Repeat hardest challenge with higher intensity",
    336: "Repeat hardest challenge with higher intensity",
    337: "Repeat hardest challenge with higher intensity",
    338: "Repeat hardest challenge with higher intensity",
    339: "Repeat hardest challenge with higher intensity",
    340: "Repeat hardest challenge with higher intensity",
    341: "Repeat hardest challenge with higher intensity",
    342: "Repeat hardest challenge with higher intensity",
    343: "Repeat hardest challenge with higher intensity",
    344: "Repeat hardest challenge with higher intensity",
    345: "Repeat hardest challenge with higher intensity",
    346: "Repeat hardest challenge with higher intensity",
    347: "Repeat hardest challenge with higher intensity",
    348: "Repeat hardest challenge with higher intensity",
    349: "Repeat hardest challenge with higher intensity",
    350: "Repeat hardest challenge with higher intensity",
    351: "Repeat hardest challenge with higher intensity",
    352: "Repeat hardest challenge with higher intensity",
    353: "Repeat hardest challenge with higher intensity",
    354: "Repeat hardest challenge with higher intensity",
    355: "Repeat hardest challenge with higher intensity",
    356: "Repeat hardest challenge with higher intensity",
    357: "Repeat hardest challenge with higher intensity",
    358: "Repeat hardest challenge with higher intensity",
    359: "Repeat hardest challenge with higher intensity",
    360: "Repeat hardest challenge with higher intensity",
    361: "Repeat hardest challenge with higher intensity",
    362: "Repeat hardest challenge with higher intensity",
    363: "Repeat hardest challenge with higher intensity",
    364: "Repeat hardest challenge with higher intensity",

    365: "Learn a new skill AND deliver a public speech confidently"
}
